# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detector.proto',
  package='',
  syntax='proto3',
  serialized_options=b'B\rdetectorProtoP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x65tector.proto\"H\n\rCamera_packet\x12 \n\x0b\x63oordinates\x18\x01 \x01(\x0b\x32\x0b.Coordinate\x12\x15\n\x05image\x18\x02 \x01(\x0b\x32\x06.Image\":\n\nCoordinate\x12\x15\n\rx_coordinates\x18\x01 \x01(\x05\x12\x15\n\ry_coordinates\x18\x02 \x01(\x05\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\"V\n\tPc_packet\x12 \n\x0b\x63oordinates\x18\x01 \x01(\x0b\x32\x0b.Coordinate\x12\x15\n\x05image\x18\x02 \x01(\x0b\x32\x06.Image\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\t28\n\x08\x64\x65tector\x12,\n\x0c\x44\x65tect_image\x12\x0e.Camera_packet\x1a\n.Pc_packet\"\x00\x42\x17\x42\rdetectorProtoP\x01\xa2\x02\x03RTGb\x06proto3'
)




_CAMERA_PACKET = _descriptor.Descriptor(
  name='Camera_packet',
  full_name='Camera_packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='Camera_packet.coordinates', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='Camera_packet.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=90,
)


_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_coordinates', full_name='Coordinate.x_coordinates', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_coordinates', full_name='Coordinate.y_coordinates', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=150,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='Image.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=174,
)


_PC_PACKET = _descriptor.Descriptor(
  name='Pc_packet',
  full_name='Pc_packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='Pc_packet.coordinates', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='Pc_packet.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='Pc_packet.class_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=262,
)

_CAMERA_PACKET.fields_by_name['coordinates'].message_type = _COORDINATE
_CAMERA_PACKET.fields_by_name['image'].message_type = _IMAGE
_PC_PACKET.fields_by_name['coordinates'].message_type = _COORDINATE
_PC_PACKET.fields_by_name['image'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['Camera_packet'] = _CAMERA_PACKET
DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Pc_packet'] = _PC_PACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Camera_packet = _reflection.GeneratedProtocolMessageType('Camera_packet', (_message.Message,), {
  'DESCRIPTOR' : _CAMERA_PACKET,
  '__module__' : 'detector_pb2'
  # @@protoc_insertion_point(class_scope:Camera_packet)
  })
_sym_db.RegisterMessage(Camera_packet)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATE,
  '__module__' : 'detector_pb2'
  # @@protoc_insertion_point(class_scope:Coordinate)
  })
_sym_db.RegisterMessage(Coordinate)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'detector_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Pc_packet = _reflection.GeneratedProtocolMessageType('Pc_packet', (_message.Message,), {
  'DESCRIPTOR' : _PC_PACKET,
  '__module__' : 'detector_pb2'
  # @@protoc_insertion_point(class_scope:Pc_packet)
  })
_sym_db.RegisterMessage(Pc_packet)


DESCRIPTOR._options = None

_DETECTOR = _descriptor.ServiceDescriptor(
  name='detector',
  full_name='detector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=264,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect_image',
    full_name='detector.Detect_image',
    index=0,
    containing_service=None,
    input_type=_CAMERA_PACKET,
    output_type=_PC_PACKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTOR)

DESCRIPTOR.services_by_name['detector'] = _DETECTOR

# @@protoc_insertion_point(module_scope)
