# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detector_pb2 as detector__pb2


class detectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect_image = channel.unary_unary(
                '/detector/Detect_image',
                request_serializer=detector__pb2.Camera_packet.SerializeToString,
                response_deserializer=detector__pb2.Pc_packet.FromString,
                )


class detectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_detectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect_image': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect_image,
                    request_deserializer=detector__pb2.Camera_packet.FromString,
                    response_serializer=detector__pb2.Pc_packet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class detector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/detector/Detect_image',
            detector__pb2.Camera_packet.SerializeToString,
            detector__pb2.Pc_packet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
