/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RobotStatus_Mode {
    RobotStatus_Mode_EXPLORATION = 0,
    RobotStatus_Mode_FASTEST_PATH = 1
} RobotStatus_Mode;

/* Struct definitions */
typedef struct _CalibrateRequest {
    char dummy_field;
} CalibrateRequest;

typedef struct _EmptyRequest {
    char dummy_field;
} EmptyRequest;

typedef struct _MapDescription {
    pb_callback_t description;
} MapDescription;

typedef struct _MetricResponse {
    pb_callback_t values;
} MetricResponse;

typedef struct _MetricRequest {
    uint32_t id;
} MetricRequest;

typedef struct _MetricResponse_ValuesEntry {
    uint32_t key;
    double value;
} MetricResponse_ValuesEntry;

typedef struct _MoveRequest {
    uint32_t step;
} MoveRequest;

typedef struct _Position {
    uint32_t x;
    uint32_t y;
} Position;

typedef struct _RobotStatus {
    RobotStatus_Mode mode;
} RobotStatus;

typedef struct _Status {
    bool status;
} Status;

typedef struct _TurnRequest {
    uint32_t angle;
} TurnRequest;


/* Helper constants for enums */
#define _RobotStatus_Mode_MIN RobotStatus_Mode_EXPLORATION
#define _RobotStatus_Mode_MAX RobotStatus_Mode_FASTEST_PATH
#define _RobotStatus_Mode_ARRAYSIZE ((RobotStatus_Mode)(RobotStatus_Mode_FASTEST_PATH+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MoveRequest_init_default                 {0}
#define Status_init_default                      {0}
#define EmptyRequest_init_default                {0}
#define TurnRequest_init_default                 {0}
#define CalibrateRequest_init_default            {0}
#define RobotStatus_init_default                 {_RobotStatus_Mode_MIN}
#define MetricRequest_init_default               {0}
#define MetricResponse_init_default              {{{NULL}, NULL}}
#define MetricResponse_ValuesEntry_init_default  {0, 0}
#define Position_init_default                    {0, 0}
#define MapDescription_init_default              {{{NULL}, NULL}}
#define MoveRequest_init_zero                    {0}
#define Status_init_zero                         {0}
#define EmptyRequest_init_zero                   {0}
#define TurnRequest_init_zero                    {0}
#define CalibrateRequest_init_zero               {0}
#define RobotStatus_init_zero                    {_RobotStatus_Mode_MIN}
#define MetricRequest_init_zero                  {0}
#define MetricResponse_init_zero                 {{{NULL}, NULL}}
#define MetricResponse_ValuesEntry_init_zero     {0, 0}
#define Position_init_zero                       {0, 0}
#define MapDescription_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define MapDescription_description_tag           1
#define MetricResponse_values_tag                1
#define MetricRequest_id_tag                     1
#define MetricResponse_ValuesEntry_key_tag       1
#define MetricResponse_ValuesEntry_value_tag     2
#define MoveRequest_step_tag                     1
#define Position_x_tag                           1
#define Position_y_tag                           2
#define RobotStatus_mode_tag                     1
#define Status_status_tag                        1
#define TurnRequest_angle_tag                    1

/* Struct field encoding specification for nanopb */
#define MoveRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   step,              1)
#define MoveRequest_CALLBACK NULL
#define MoveRequest_DEFAULT NULL

#define Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     status,            1)
#define Status_CALLBACK NULL
#define Status_DEFAULT NULL

#define EmptyRequest_FIELDLIST(X, a) \

#define EmptyRequest_CALLBACK NULL
#define EmptyRequest_DEFAULT NULL

#define TurnRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   angle,             1)
#define TurnRequest_CALLBACK NULL
#define TurnRequest_DEFAULT NULL

#define CalibrateRequest_FIELDLIST(X, a) \

#define CalibrateRequest_CALLBACK NULL
#define CalibrateRequest_DEFAULT NULL

#define RobotStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define RobotStatus_CALLBACK NULL
#define RobotStatus_DEFAULT NULL

#define MetricRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define MetricRequest_CALLBACK NULL
#define MetricRequest_DEFAULT NULL

#define MetricResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            1)
#define MetricResponse_CALLBACK pb_default_field_callback
#define MetricResponse_DEFAULT NULL
#define MetricResponse_values_MSGTYPE MetricResponse_ValuesEntry

#define MetricResponse_ValuesEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             2)
#define MetricResponse_ValuesEntry_CALLBACK NULL
#define MetricResponse_ValuesEntry_DEFAULT NULL

#define Position_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2)
#define Position_CALLBACK NULL
#define Position_DEFAULT NULL

#define MapDescription_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    description,       1)
#define MapDescription_CALLBACK pb_default_field_callback
#define MapDescription_DEFAULT NULL

extern const pb_msgdesc_t MoveRequest_msg;
extern const pb_msgdesc_t Status_msg;
extern const pb_msgdesc_t EmptyRequest_msg;
extern const pb_msgdesc_t TurnRequest_msg;
extern const pb_msgdesc_t CalibrateRequest_msg;
extern const pb_msgdesc_t RobotStatus_msg;
extern const pb_msgdesc_t MetricRequest_msg;
extern const pb_msgdesc_t MetricResponse_msg;
extern const pb_msgdesc_t MetricResponse_ValuesEntry_msg;
extern const pb_msgdesc_t Position_msg;
extern const pb_msgdesc_t MapDescription_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MoveRequest_fields &MoveRequest_msg
#define Status_fields &Status_msg
#define EmptyRequest_fields &EmptyRequest_msg
#define TurnRequest_fields &TurnRequest_msg
#define CalibrateRequest_fields &CalibrateRequest_msg
#define RobotStatus_fields &RobotStatus_msg
#define MetricRequest_fields &MetricRequest_msg
#define MetricResponse_fields &MetricResponse_msg
#define MetricResponse_ValuesEntry_fields &MetricResponse_ValuesEntry_msg
#define Position_fields &Position_msg
#define MapDescription_fields &MapDescription_msg

/* Maximum encoded size of messages (where known) */
#define MoveRequest_size                         6
#define Status_size                              2
#define EmptyRequest_size                        0
#define TurnRequest_size                         6
#define CalibrateRequest_size                    0
#define RobotStatus_size                         2
#define MetricRequest_size                       6
/* MetricResponse_size depends on runtime parameters */
#define MetricResponse_ValuesEntry_size          15
#define Position_size                            12
/* MapDescription_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
