/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MoveRequest, MoveRequest, AUTO)


PB_BIND(Status, Status, AUTO)


PB_BIND(EmptyRequest, EmptyRequest, AUTO)


PB_BIND(TurnRequest, TurnRequest, AUTO)


PB_BIND(CalibrateRequest, CalibrateRequest, AUTO)


PB_BIND(RobotStatus, RobotStatus, AUTO)


PB_BIND(MetricRequest, MetricRequest, AUTO)


PB_BIND(MetricResponse, MetricResponse, AUTO)


PB_BIND(MetricResponse_ValuesEntry, MetricResponse_ValuesEntry, AUTO)


PB_BIND(Position, Position, AUTO)


PB_BIND(MapDescription, MapDescription, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif